{
 "title": "DevOps Lab",
 "tags": [ "devops-lab" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lab_http_requests_total{namespace=\"lab-helm\"}[2m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Server error rate (5xx %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(lab_http_requests_total{namespace=\"lab-helm\",status=~\"5..\"}[2m])) or vector(0))\n/ clamp_min(sum(rate(lab_http_requests_total{namespace=\"lab-helm\"}[2m])), 0.001)",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(lab_http_request_duration_seconds_bucket{namespace=\"lab-helm\"}[2m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])))",
     "legendFormat": "node CPU %"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "node RAM %"
    }
   ]
  },
  {
   "title": "API available replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"lab-helm\",deployment=\"api\"}",
     "legendFormat": "available replicas"
    }
   ]
  }
 ]
}